### ISSUE TITLE
Fix react example

### ISSUE THREAD

**Issue by akim-muto** [tomjs/vite-plugin-vscode#13]
Fix react example.
https://github.com/tomjs/vite-plugin-vscode/pull/12

There is double management with the code generated by @tomjs/create-app and the samples in this repository.
If possible, it would be better to have it automatically rewrite the other place when you change one place.

I didn't have the energy to go that far.😂

PS: The PR is just a summary of what I've tried, so if you want to organize the directory or automate the rewriting, you don't need to worry about it.

**Comment by tomgao365** [comment]
Multiple acquireVsCodeApi() instances will conflict, thanks to PR #12
