### ISSUE TITLE
使用 `import.meta.env` 替换 `process.env`

### ISSUE THREAD

**Issue by typed-sigterm** [tomjs/vite-plugin-vscode#15]
前两天按例子写 `process.env.VITE_DEV_SERVER_URL` 时，ESLint 报错要求写 `import process from 'node:process'`，然后 tsup 环境变量替换就失效了，查了一个小时才发现问题 qwq

Vite 一直推荐使用 `import.meta.env`，它更能确保环境变量正确替换，也许可以考虑一下替换掉 `process.env`？尝试了 PR，但是不知道 `env.d.ts` 怎么改（我太菜了

link https://github.com/egoist/tsup/pull/1230

**Comment by tomgao365** [comment]
@typed-sigterm 额，`vscode` 的 `node` 代码是用 `tsup/esbuild` 打包的，和 `vite` 的 `import.meta.env` 没太大关系。
关于 `import process from 'node:process'` 的 `eslint` 规则的问题，要不禁用掉😂，毕竟规则是死的，也要看是否适合自己。

**Comment by typed-sigterm** [comment]
> @typed-sigterm 额，`vscode` 的 `node` 代码是用 `tsup/esbuild` 打包的，和 `vite` 的 `import.meta.env` 没太大关系。
> 关于 `import process from 'node:process'` 的 `eslint` 规则的问题，要不禁用掉😂，毕竟规则是死的，也要看是否适合自己。
> 

（是因为 tsup 发现 `process` 被 import 的值覆盖掉了，所以没有替换 `process.env`，`import.meta.env` 因为不是变量，不会有类似的问题）
