### ISSUE TITLE
能提供一个使用 nuxt 的示例吗

### ISSUE THREAD

**Issue by 171h** [tomjs/vite-plugin-vscode#17]
https://nuxt.com/

**Comment by typed-sigterm** [comment]
这种情况强烈推荐使用 [`unplugin-vue-router`](https://npmjs.com/package/unplugin-vue-router)

用了两年 Nuxt，它是个完整的解决方案，个人认为像 VSCode 插件这种非全栈又无需 SSR 的场景，纯 Vue 就可以了
