### ISSUE TITLE
sveltte for webview

### ISSUE THREAD

**Issue by tigawanna** [tomjs/vite-plugin-vscode#19]
tried to set it up using svelte and got [this far](https://github.com/tigawanna/vscode-svelte-webview)
any help to get it working , it keeps crashing with module type errors but works as a SPA site

**Comment by tomgao365** [comment]
@tigawanna 

Note: extensions are not impacted by this change and not loaded via ESM, please see
* https://github.com/microsoft/vscode/issues/130367
* https://code.visualstudio.com/updates/v1_94#_esm-is-shipping-for-vs-code

**Comment by tigawanna** [comment]
looks like am getting console warnings about only react and vuw support

11:23:14 [tomjs:vscode] Only support react or vue!
11:23:17 [tomjs:vscode] Only support react or vue!

i got it woking with preact though

**Comment by tomgao365** [comment]
@tigawanna
This is my mistake. v3.0 adds support for react-devtools and vue-devtools standalone applications. This is a warning that devtools configuration is not supported. In addition to devtools, `vite-plugin-vscode` supports all programming languages ​​supported by vite.

**Comment by tigawanna** [comment]
nice
