### ISSUE TITLE
pdf-parse doesn't work when bundling

### ISSUE THREAD

**Issue by SwiftWinds** [tomjs/vite-plugin-vscode#20]
## Description

I'm getting this issue when trying to use `pdf-parse`:

![image](https://github.com/user-attachments/assets/00bd5e58-6718-41c4-b3df-993a08fc694d)

Here is a minimal example of this issue happening: https://github.com/SwiftWinds/pdf-parse-not-working-minimal-example

Note that this doesn't happen when you hit `F5` to debug. However, it fails when you `pnpm build && pnpm dlx @vscode/vsce package --no-dependencies` and install the VSIX.

I bet it's because there's this one `require()` statement in the library code:

<img width="1309" alt="image" src="https://github.com/user-attachments/assets/fae3b719-5811-42f8-8126-3284c9b54517">

But I would expect vite and this plugin to be able to handle that correctly. Any suggestions or workarounds?

## Steps to reproduce

1. `git clone https://github.com/SwiftWinds/pdf-parse-not-working-minimal-example.git`
2. `cd pdf-parse-not-working-minimal-example`
3. `pnpm i`
4. `pnpm build && pnpm dlx @vscode/vsce package --no-dependencies`
5. `code --install-extension ./template-react-0.0.0.vsix`
6. `cmd + shift + p` and type "Hello World: Parse PDF", select a PDF, and observe the error.

**Comment by tomgao365** [comment]
@SwiftWinds There are 2 solutions, but I don't know if they can meet your needs.
1.An inelegant way to copy related dependencies to the target directory.

```ts
import { defineConfig } from 'vite';
import path from 'path';
import fs from 'fs';
import vscode from '@tomjs/vite-plugin-vscode';
import react from '@vitejs/plugin-react-swc';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    vscode({
      extension: {
        async onSuccess() {
          const dest = path.join(__dirname, 'dist/extension');
          const filter = (source: string, destination: string) => {
            return !['.map', '.md'].find(ext => destination.endsWith(ext));
          };
          fs.cpSync(
            path.join(__dirname, 'node_modules/pdf-parse/lib/pdf.js/v1.10.100'),
            path.join(dest, 'pdf.js/v1.10.100'),
            { recursive: true, filter },
          );
          fs.cpSync(
            path.join(__dirname, 'node_modules/.pnpm/node-ensure@0.0.0/node_modules/node-ensure'),
            path.join(dest, 'node_modules/node-ensure'),
            { recursive: true, filter },
          );
        },
      },
    }),
  ],
});
```

2. Similar to [@tomjs/vite-plugin-electron](https://github.com/tomjs/vite-plugin-electron)
* Copy the built `dist` and `package.json` to a temporary directory
* Modify dependencies, remove dependencies, and execute `npm install`
* Execute `vsce pack`

**Comment by SwiftWinds** [comment]
Thanks for your quick response! I'm wondering -- why is this problem even a thing? Is the bundler unable to realize that the pdf.js file is `require`'ed when it's not top level?

**Comment by tomgao365** [comment]
@SwiftWinds 
The path of require() is a variable parameter, so if it is a constant, there should be no problem.It is now recommended to use es module, esbuild and other tools that can parse the code and remove useless code.

**Comment by SwiftWinds** [comment]
> if it is a constant, there should be no problem

ah so if I use `pnpm` to patch the package and hardcode the `require` to use version 1.10.100, it would work?

**Comment by tomgao365** [comment]
This is also an idea, you can try it.
