### ISSUE TITLE
Using copy/paste and contextmenu inside vite webview

### ISSUE THREAD

**Issue by craigrileyuk** [tomjs/vite-plugin-vscode#21]
At the moment, it seems like the webview provided captures any and all mouse events or keyboard events, blocking them from reaching VSCode.

This means that to do any of the following, you have click outside the webview

1. Use keyboard shortcuts, like the command palette.
2. Access the mouse contextmenu (for copy,paste,cut)
3. Use standard keyboard functions like copy/paste.

This seems to be discussed here: https://github.com/microsoft/vscode/issues/65452

Is it possible to proxy these events between the vite iframe and the vscode webview?

**Comment by tomgao365** [comment]
@craigrileyuk 
I bought a Mac mini and tried to solve these problems in the macOS environment today.
The F1/Copy/Paste/Cut/Undo/Redo commands are now supported, but contextMenu is currently unresolved.

**Comment by craigrileyuk** [comment]
Wow. That's above and beyond for sure.

Thank you so much. I didn't realise that it was a MacOS only situation.

**Comment by tomgao365** [comment]
Glad to help you
