### ISSUE TITLE
bug in `getWebviewNpmPath`

### ISSUE THREAD

**Issue by subframe7536** [tomjs/vite-plugin-vscode#4]
https://github.com/tomjs/vite-plugin-vscode/blob/c49025cb246e8f339686927359d8d38e4ab0e8d8/src/utils.ts#L145-L147

this snippet should move outside the scope of `if (!fs.existsSync(npmPath))`

**Comment by tomgao365** [comment]
@subframe7536 
I also discovered this problem at noon and planned to solve it in the evening. 😄
Try the latest version.
