### ISSUE TITLE
weird delay in dev mode

### ISSUE THREAD

**Issue by subframe7536** [tomjs/vite-plugin-vscode#5]
Thanks for your great works!

It seems that the plugin patch the `acquireVsCodeApi` function in dev mode. It cause weird delay on startup and I have to rerun the function in `setImmediate(setTimeout())`. And the prod mode have nothing wrong.

My code is [here](https://github.com/subframe7536/vscode-codeimg)

**Comment by tomgao365** [comment]
@subframe7536 
Thank you very much for using this library. I'm ashamed that I wanted to use it to develop extensions, but I didn't start for some reason.
Sorry, I don't have a good solution for now. 
Development mode uses [@tomjs/tomjs/vscode-extension-webview](https://github.com/tomjs/vscode-extension-webview) to implement it, which is actually an iframe. The client's `acquireVsCodeApi` is simulated and uses window.postMessage to communicate with the parent.
Could you provide some better ideas? Thanks!

**Comment by tomgao365** [comment]
@subframe7536 Try v2.5.0 to see if it solves your problem

**Comment by subframe7536** [comment]
OK, I will check it out this weekend

**Comment by subframe7536** [comment]
Same...🤔

**Comment by tomgao365** [comment]
😂
Alas, I have no solution for now. My experimental project uses this, and it is fine during the development stage.
https://github.com/tomjs/vscode-snippets-manager

**Comment by subframe7536** [comment]
I just release the first version of my extension, and this issue just cause little DX problem. So I plan to close it. Thanks again for your great works!
