### ISSUE TITLE
doesn't work workspaces, suggestion fix provided

### ISSUE THREAD

**Issue by derekrjones** [tomjs/vite-plugin-vscode#7]
`getWebviewNpmPath()` fails in yarn workspaces since `WEBVIEW_PACKAGE_NAME` is hoisted to root `node_modules` dir.
I was successfully able to get it running by

```js
const clientFile = require.resolve(`${WEBVIEW_PACKAGE_NAME}/client`);
if (!fs.existsSync(clientFile)) { 
  logger.warn(`[${WEBVIEW_PACKAGE_NAME}] is not installed, please install it first!`);
} else { 
  devWebviewClient = fs.readFileSync(clientFile, 'utf-8'); 
} 
```
which can then remove all of...

https://github.com/tomjs/vite-plugin-vscode/blob/94057884d33f8da730561455e9d45d396817f32b/src/utils.ts#L111-L141

https://github.com/tomjs/vite-plugin-vscode/blob/94057884d33f8da730561455e9d45d396817f32b/src/index.ts#L212-L231

**Comment by tomgao365** [comment]
😄Thank you very much for your use and questions.
😂Sorry, I was busy participating in China's 6.18 Shopping Festival and didn't notice your feedback.
Please try the new version to see if it solves your problem. (By Google)

**Comment by derekrjones** [comment]
working great! thanks for the quick release!
