### ISSUE TITLE
env.d.ts  can not find type definition file

### ISSUE THREAD

**Issue by derekrjones** [tomjs/vite-plugin-vscode#8]
in any of the examples, there is extension/env.d.ts
https://github.com/tomjs/vite-plugin-vscode/blob/94057884d33f8da730561455e9d45d396817f32b/examples/react/extension/env.d.ts#L1
this seems to work fine in your workspace,
I see it listed in 'files' in `package.json`
but when used an external project `env` cannot be found. I'm guessing because its not part of the exports
https://github.com/tomjs/vite-plugin-vscode/blob/94057884d33f8da730561455e9d45d396817f32b/package.json#L24-L34
It works if I include it in exports
```json
  "exports": {
    ".": {
      "require": "./dist/index.js",
      "import": "./dist/index.mjs",
      "types": "./dist/index.d.ts"
    },
    "./env": {
      "types": "./env.d.ts"
    }
  },
```

**Comment by tomgao365** [comment]
Please try v2.4.0

**Comment by derekrjones** [comment]
working great! thanks for the quick release!
